### ISSUE TITLE
Use the term "artifact" test instead of "integration"

### ISSUE THREAD

**Issue by daved** [OpenEugene/openboard#102]
- [x] Use "artifact" instead of "integration"
- [x] Move `tests/cmd/openbsrv-integration` to `tests/openbsrv` to mirror the `cmd/openbsrv` dir (which is what is being tested)
- [x] Ensure tests still run successfully

**Comment by coatsd** [comment]
Currently running into this error when trying to run artifact testing:
![image](https://user-images.githubusercontent.com/35239532/99856328-9bb10080-2b3d-11eb-8356-92a9f00b9d8b.png)
It looks like there's a relative path check somewhere in artifact_test.go that needs the location of a go.mod file in the back/internal directory. I'm not sure where it's at yet.
