### ISSUE TITLE
Clarify protoc version if needed

### ISSUE THREAD

**Issue by daved** [OpenEugene/openboard#117]
I'm currently running protoc 3.11.4. If this is important, the version should be noted in docs. If it is not important, that should also be noted

AC
- [ ] Update the doc with protoc version or note indicating it does not matter which

**Comment by daved** [comment]
@codegold79, @coatsd: Please let me know what protoc version you're using.

**Comment by codegold79** [comment]
> @codegold79, @coatsd: Please let me know what protoc version you're using.

@daved, here is what I have that I used to run `gengo`:

```
$ protoc --version
libprotoc 3.9.1
```

**Comment by daved** [comment]
I'm on 3.11.4.
@coatsd a bump for this info

**Comment by coatsd** [comment]
I'm running 3.14.0

**Comment by daved** [comment]
Closing in favor of #130
