### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by nqthqn** [OpenEugene/openboard#13]
https://docs.travis-ci.com/user/languages/elm

@champagneabuelo You might need to grant some access.

**Comment by daved** [comment]
What need does this serve for such a small project? I'd argue that we won't need this until there are, at least, integrated tests (behavior and/or integration). Deployment build steps that complicate the local environment (e.g. containers... but why?) would also be slightly compelling.

We should be expected to be writing and running tests locally. So a deployment can have a simple bot running that, as needed, pulls from master or downloads latest release executables.

Also, Travis has recently earned a bad rep (With a sort of boycott going on.): https://www.reddit.com/r/programming/comments/atjltu/layoffs_at_travis_ci_their_team_was_being/

**Comment by nqthqn** [comment]
> What need does this serve for such a small project?

For new contributors it encourages quality code. Their PR can't be merged until the tests pass. It's a simple reminder that we test our code before merging into master.

> We should be expected to be writing and running tests locally.

Indeed — and this would encourage testing for new contributors. 

> So a deployment can have a simple bot running that, as needed, pulls from master or downloads latest release executables.

This would not prevent that.

> Also, Travis has recently earned a bad rep (With a sort of boycott going on.):

Fair. Perhaps Circle CI would be another option. Travis has good Elm support.

**Comment by nqthqn** [comment]
That said — I agree it's not something we need right away.

If a new contributor who has not run the tests locally opens a PR it gives us visibility into any potential problems. An automated safety precaution to ease the chaos of collaboration.

**Comment by daved** [comment]
CircleCI, in general, does seem like the common alternative at the moment. If the Elm support is sufficient, that would have my vote.

**Comment by champagneabuelo** [comment]
I've worked with Circle CI in the past, and they also provide some extra containers for open source projects! https://circleci.com/docs/2.0/oss/
I'm leaning towards Circle, but it seems that some people have had some issues building Elm on it: https://discuss.circleci.com/t/building-elm-applications-is-incredibly-slow-in-circleci-containers/3804/3
