### ISSUE TITLE
Update the AUTHORS document to include all contributors so far

### ISSUE THREAD

**Issue by annag42** [OpenEugene/openboard#140]
The AUTHORS document [1] [2] is outdated, as new contributors [3] have added to the code in this repository but are not yet listed in that document. It could be updated by adding those recent contributors, especially the two who confirmed their preferred display names during a recent meeting ("Daniel Coats" and "Alex Anderson").

[1] AUTHORS document file path (within this repository): 
./blob/main/docs/AUTHORS

[2] AUTHORS document URL, on Github: 
https://github.com/OpenEugene/openboard/blob/main/docs/AUTHORS

[3] Current list of contributors to this repository, according to Github: 
https://github.com/OpenEugene/openboard/graphs/contributors

**Comment by codegold79** [comment]
Thanks @annag42 for taking this on. I have a question: could you also put an '@' sign before my github handle?

**Comment by daved** [comment]
Closed by #155
