### ISSUE TITLE
Start service: Posts

### ISSUE THREAD

**Issue by mckelveygreg** [OpenEugene/openboard#29]
This is a working issue that tracks starting a service for new Posts, aka "Asks" and "Offers"
Data Structure:
- 

mini-Services?
-

**Comment by mckelveygreg** [comment]
I'm starting to build out the front end. What data fields will I need to include in the front-end form?

**Comment by nqthqn** [comment]
```
{
  "title": "Hello World",
  "body": "## Markdown\n",
  "slug": "hello-world",
  "id": 24,
  "isAsk": true,
  "tags": [
    "elm",
    "go"
  ]
}
```

**Comment by mckelveygreg** [comment]
Follow [user.proto](https://github.com/OpenEugene/openboard/blob/master/msgs/proto/user.proto) as an example for new posts.proto

**Comment by codegold79** [comment]
I started PR #49 to build the post service. I'm basing my work on PR #42, which is for the post.proto file.

**Comment by daved** [comment]
Stale
