### ISSUE TITLE
Gain contributors by creating special issues for MozSprint 

### ISSUE THREAD

**Issue by nohorse** [OpenEugene/openboard#40]
Mozsprint is happing for the rest of May. To gain some visibility it would be great to have some issues labeled with "help wanted", "good first issue", "mozsprint" and "openeugene".

Purpose
To help local open source projects in Eugene, OR gain visibility and contributors from the greater open source community, and enabling local open source enthusiasts to find local projects for contribution.  

Outcome
Local open source projects have worldwide visibility, clear paths to collaboration and have gained new collaborators.

Process
- Add issues that are attractive to new collaborators by labeling them as "help wanted"
- Create simple issues that inexperienced folks can tackle and label them as "good first issue" 
- Attract global contributors by and labeling issues with "mozsprint" 
- Attract local contributors by and labeling issues with "openeugene"

feel free to start a conversation in the comments below!  🎉

**Comment by daved** [comment]
done enough
