### ISSUE TITLE
Design Mockups

### ISSUE THREAD

**Issue by mckelveygreg** [OpenEugene/openboard#41]
Checkout these mock ups and open up an issue to claim a piece of UI!
[Openboard.pdf](https://github.com/OpenEugene/openboard/files/3159964/Openboard.pdf)
- [ ] Home
- [ ] Login
- [ ] Sign up
- [ ] Reset Password
- [ ] Confirmation Screen
- [ ] Edit Account
- [ ] New Ask/offer (post) @mckelveygreg 
- [ ] Ask/offer (post)

**Comment by daved** [comment]
stale / closing in favor of other and future issues
