### ISSUE TITLE
Illustrations

### ISSUE THREAD

**Issue by nqthqn** [OpenEugene/openboard#44]
Free!
https://undraw.co/illustrations

![Screen Shot 2019-06-07 at 2 03 26 PM](https://user-images.githubusercontent.com/857356/59133485-0b710280-892d-11e9-9ca6-66f36820e749.png)

[Archive.zip](https://github.com/OpenEugene/openboard/files/3267608/Archive.zip)

**Comment by nqthqn** [comment]
Illustrations
https://lukaszadam.com/illustrations
https://absurd.design/
https://gallery.manypixels.co/

Pictures
https://www.pexels.com/search/computer/
https://unsplash.com/

Icons
https://fontawesome.com/

**Comment by daved** [comment]
future frontend contributors will need to address this much later
