### ISSUE TITLE
update the readme with a quick getting started checklist

### ISSUE THREAD

**Issue by nohorse** [OpenEugene/openboard#5]
for folks who don't know how to build Elm, it would be handy to have some steps in the repo to get up and running quickly.  see https://github.com/EugTech/OpenEugeneFestivalWeb for an example.

# OpenEugeneFestivalWeb

This is an attempt at utilizing Gatsby, a React.js static site generator.

This site will be following the layout of [mozillafestival.org] and design styles from the [Gatsby Get up and Running Tutorial](https://www.gatsbyjs.org/tutorial)

## Getting Started

To get started, clone and...

```sh
npm install
npm gatsby develop
```

## Deploy

The site is hosted by Github Pages at [https://eugtech.github.io/OpenEugeneFestivalWeb/](https://eugtech.github.io/OpenEugeneFestivalWeb/)

The `gh-pages` package is installed, so to deploy new changes, simply:

```sh
npm run deploy
```

**Comment by nqthqn** [comment]
I think having some helpful instructions in the global README will be a great addition. We will need to add some tool around getting the backend and frontend up easily. I've updated the README for the frontend:

https://github.com/champagneabuelo/openboard/tree/elmcss-protobuf/front

Thoughts?

**Comment by champagneabuelo** [comment]
The instructions looks great! I think it might be better to put them as a separate README in the `front` directory, so that the main README can contain more general information about the project itself.
Also, we'll be able to get the frontend up with the additions in @daved's PR (#12)!

**Comment by daved** [comment]
Done enough for now.
