### ISSUE TITLE
Separate out basic message types from response types

### ISSUE THREAD

**Issue by daved** [OpenEugene/openboard#53]
Currently, there are the message types "UserResp" and "UsersResp". The "UsersResp" has a collection/repeated field called "Items" that is of type "UserResp". For consistency, please create a "User" type that is used as the type in the "Items" field. Similarly, "UserResp" should be updated to have a field called "Item" that is of type "User".

**Comment by codegold79** [comment]
Will combine PRs #53 and #54 and name the branch and PRs to be closer to issue.
