### ISSUE TITLE
back: Remove explicit db.Prepare usage in User Service

### ISSUE THREAD

**Issue by daved** [OpenEugene/openboard#85]
Spawning from #74

**Comment by codegold79** [comment]
@coatsd and I reviewed the usage of `db.Prepare` in the user service query code, and we found one instance of it. It was used for inserting `user_id` and `role_id` into the join table called `user_role`. 

According to the the tutorial section "Modifying Data and Using Transactions" in the [Go Database/SQL Tutorials site](http://go-database-sql.org/modifying.html), for executing statements that do not return data, such as `INSERT` statements, using `db.Prepare` is preferred. The other option, to simply use `Exec` does not provide the parameter binding we desire.

We believe this issue can be closed as it has been completed.
