### ISSUE TITLE
Pathways exist for collaborators

### ISSUE THREAD

**Issue by daved** [OpenEugene/openboard#88]
Blocked by #89

Based on this conversation: https://eugenetech.slack.com/archives/CKWAJL9MM/p1596660601237400

Once more proven procedures and relevant docs are in place, ensure pathways exist for new collaborators.

AC
TBD

**Comment by daved** [comment]
I'd like the project to maintain its current trajectory while slightly increasing momentum. Therefore, I'd like to close this for now.  @codegold79 , if you agree, please close/close-with-comment.

**Comment by codegold79** [comment]
I agree that we don't need more pathways for new collaborators. We've been having a steady flow of new collaborators without having to advertise our project on other sites.
